// This file is kept in sync with /data.json.
// 100 total events: 5 states × 4 categories × 5 events each
// Movies → Theatre | Shows → Hall | Concerts → Stadium | Events → Arena
// Run: npm run db:seed

export const seedEvents = [

  // ════════════════════════════════════════════════════════════════════════════
  //  TAMIL NADU — 20 events
  // ════════════════════════════════════════════════════════════════════════════

  // ── Tamil Nadu · Movies (Theatre) ───────────────────────────────────────────
  {
    title: "Coolie",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800",
    date: "2026-07-15T00:00:00Z",
    time: "Various Timings",
    location: "PVR IMAX Theatre, Chennai, Tamil Nadu",
    rating: "4.9",
    description: "Rajinikanth stars in this high-octane action thriller directed by Lokesh Kanagaraj. Breathtaking action sequences in a pan-India backdrop.",
    price: 35000,
    organizer: "Sun Pictures",
    features: ["Dolby Atmos", "Recliner Seats", "Free Popcorn Combo"],
    crew: [
      { name: "Lokesh Kanagaraj", role: "Director", img: "https://ui-avatars.com/api/?name=Lokesh+Kanagaraj&background=random&size=200" },
      { name: "Rajinikanth", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Rajinikanth&background=random&size=200" }
    ],
    reviews: [{ name: "Ashwin", rating: 5, comment: "Pure mass! The BGM is absolutely lit." }]
  },
  {
    title: "Vikram 2",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    date: "2026-07-28T00:00:00Z",
    time: "Various Timings",
    location: "INOX Cineplex Theatre, Chennai, Tamil Nadu",
    rating: "4.8",
    description: "Kamal Haasan returns in the explosive sequel to Vikram, unmasking a deeper conspiracy that threatens the nation. Lokesh Cinematic Universe expands.",
    price: 40000,
    organizer: "Raaj Kamal Films",
    features: ["4K Laser", "Dolby Vision", "Premium Recliners"],
    crew: [
      { name: "Lokesh Kanagaraj", role: "Director", img: "https://ui-avatars.com/api/?name=Lokesh+Kanagaraj&background=random&size=200" },
      { name: "Kamal Haasan", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Kamal+Haasan&background=random&size=200" }
    ],
    reviews: [{ name: "Deepa", rating: 5, comment: "Kamal sir at his absolute best!" }]
  },
  {
    title: "Thalapathy 69",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800",
    date: "2026-08-12T00:00:00Z",
    time: "Various Timings",
    location: "Sathyam Cinemas Theatre, Chennai, Tamil Nadu",
    rating: "4.7",
    description: "Vijay's comeback film after announcing political entry — a mass entertainer packed with emotional depth and power-packed action.",
    price: 38000,
    organizer: "AGS Entertainment",
    features: ["3D Experience", "Snack Hamper", "VIP Lounge"],
    crew: [
      { name: "Venkat Prabhu", role: "Director", img: "https://ui-avatars.com/api/?name=Venkat+Prabhu&background=random&size=200" },
      { name: "Thalapathy Vijay", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Thalapathy+Vijay&background=random&size=200" }
    ],
    reviews: [{ name: "Surya", rating: 5, comment: "Thalapathy magic all the way!" }]
  },
  {
    title: "Suriya 44",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800",
    date: "2026-09-03T00:00:00Z",
    time: "Various Timings",
    location: "AGS Cinemas Theatre, Chennai, Tamil Nadu",
    rating: "4.6",
    description: "Suriya's 44th film directed by Karthik Subbaraj — a gripping thriller with deep social commentary wrapped in intense drama.",
    price: 33000,
    organizer: "2D Entertainment",
    features: ["Dolby Atmos", "Luxury Seating", "Collectible Poster"],
    crew: [
      { name: "Karthik Subbaraj", role: "Director", img: "https://ui-avatars.com/api/?name=Karthik+Subbaraj&background=random&size=200" },
      { name: "Suriya", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Suriya&background=random&size=200" }
    ],
    reviews: [{ name: "Rekha", rating: 5, comment: "Karthik Subbaraj never disappoints!" }]
  },
  {
    title: "Dhanush 51",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800",
    date: "2026-09-20T00:00:00Z",
    time: "Various Timings",
    location: "Escape Cinemas Theatre, Chennai, Tamil Nadu",
    rating: "4.7",
    description: "Dhanush in a dual role — a rural action saga and urban drama woven into one unforgettable narrative directed by Mari Selvaraj.",
    price: 30000,
    organizer: "Kalaippuli S Thanu",
    features: ["Recliner Seats", "Dolby Sound", "Opening Day Special"],
    crew: [
      { name: "Mari Selvaraj", role: "Director", img: "https://ui-avatars.com/api/?name=Mari+Selvaraj&background=random&size=200" },
      { name: "Dhanush", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Dhanush&background=random&size=200" }
    ],
    reviews: [{ name: "Arun", rating: 5, comment: "Emotionally gripping from start to end." }]
  },

  // ── Tamil Nadu · Shows (Hall) ────────────────────────────────────────────────
  {
    title: "Zakir Khan Live",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800",
    date: "2026-07-18T00:00:00Z",
    time: "7:00 PM",
    location: "Kalaivanar Arangam Hall, Chennai, Tamil Nadu",
    rating: "4.8",
    description: "The king of Hindustani comedy brings his 'Sakht Launda' persona to Chennai — an evening of pure laughter and relatability.",
    price: 80000,
    organizer: "OML Entertainment",
    features: ["Reserved Seating", "Meet & Greet Pass", "Merchandise"],
    crew: [{ name: "Zakir Khan", role: "Stand-up Comedian", img: "https://ui-avatars.com/api/?name=Zakir+Khan&background=random&size=200" }],
    reviews: [{ name: "Ananya", rating: 5, comment: "Laughed non-stop for 2 hours straight!" }]
  },
  {
    title: "Praveen Kumar Comedy Night",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-08-02T00:00:00Z",
    time: "7:30 PM",
    location: "Sri Krishna Gana Sabha Hall, Chennai, Tamil Nadu",
    rating: "4.6",
    description: "Tamil Nadu's most popular stand-up comedian Praveen Kumar delivers a laugh-out-loud show packed with local humour and cultural wit.",
    price: 60000,
    organizer: "Drama Queen Productions",
    features: ["Front Row VIP", "Raffle Draw", "Signed Poster"],
    crew: [{ name: "Praveen Kumar", role: "Comedian", img: "https://ui-avatars.com/api/?name=Praveen+Kumar&background=random&size=200" }],
    reviews: [{ name: "Ranjani", rating: 5, comment: "Tears of laughter! Absolutely brilliant." }]
  },
  {
    title: "Madras Improv Collective",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    date: "2026-08-20T00:00:00Z",
    time: "6:30 PM",
    location: "Narada Gana Sabha Hall, Chennai, Tamil Nadu",
    rating: "4.5",
    description: "An ensemble of Chennai's top improv comedians perform audience-driven sketches, character pieces, and long-form improv storytelling.",
    price: 50000,
    organizer: "The Laughter Club",
    features: ["Interactive Format", "Audience Participation", "Post-show Mixer"],
    crew: [{ name: "Sharath Raju", role: "Troupe Director", img: "https://ui-avatars.com/api/?name=Sharath+Raju&background=random&size=200" }],
    reviews: [{ name: "Meenakshi", rating: 5, comment: "So spontaneous and hilarious!" }]
  },
  {
    title: "Tamil Drama Ulagam",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    date: "2026-09-07T00:00:00Z",
    time: "6:00 PM",
    location: "Valluvar Kottam Hall, Chennai, Tamil Nadu",
    rating: "4.7",
    description: "A premier Tamil theatrical drama presenting three classic plays by legendary playwrights, performed by Chennai's finest theatre troupe.",
    price: 45000,
    organizer: "Chennai Theatre Guild",
    features: ["Traditional Seating", "Programme Booklet", "Refreshments Included"],
    crew: [{ name: "K. Balaji", role: "Stage Director", img: "https://ui-avatars.com/api/?name=K+Balaji&background=random&size=200" }],
    reviews: [{ name: "Venkatesan", rating: 5, comment: "Theatre at its finest in Tamil Nadu." }]
  },
  {
    title: "Karthik Kumar: Aansplaining",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-09-22T00:00:00Z",
    time: "8:00 PM",
    location: "Museum Theatre Hall, Chennai, Tamil Nadu",
    rating: "4.8",
    description: "Chennai's beloved bilingual comedian Karthik Kumar brings sharp social commentary and explosive humour in his brand-new solo show.",
    price: 70000,
    organizer: "Evam Entertainment",
    features: ["Premium Seats", "Special Edition Merch", "Pre-show Reception"],
    crew: [{ name: "Karthik Kumar", role: "Comedian & Writer", img: "https://ui-avatars.com/api/?name=Karthik+Kumar&background=random&size=200" }],
    reviews: [{ name: "Preethi", rating: 5, comment: "His timing and delivery is just chef's kiss!" }]
  },

  // ── Tamil Nadu · Concerts (Stadium) ─────────────────────────────────────────
  {
    title: "A.R. Rahman: Harmony Live",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800",
    date: "2026-07-22T00:00:00Z",
    time: "6:00 PM",
    location: "Jawaharlal Nehru Stadium, Chennai, Tamil Nadu",
    rating: "5.0",
    description: "The Mozart of Madras performs his greatest hits live — a once-in-a-lifetime concert with full orchestra and special guest appearances.",
    price: 150000,
    organizer: "Times Live",
    features: ["Full Orchestra", "VIP Golden Circle", "Commemorative Wristband"],
    crew: [{ name: "A.R. Rahman", role: "Composer & Performer", img: "https://ui-avatars.com/api/?name=AR+Rahman&background=random&size=200" }],
    reviews: [{ name: "Sanjana", rating: 5, comment: "Goosebumps throughout. A divine experience." }]
  },
  {
    title: "Sid Sriram: Soul Unplugged",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    date: "2026-08-05T00:00:00Z",
    time: "7:00 PM",
    location: "Nehru Indoor Stadium, Chennai, Tamil Nadu",
    rating: "4.9",
    description: "Sid Sriram performs his soul-stirring Tamil compositions live in an intimate acoustic format with ambient visuals and full band.",
    price: 100000,
    organizer: "Qube Concerts",
    features: ["Acoustic Zone", "LED Backdrop", "Artist Signed Poster"],
    crew: [{ name: "Sid Sriram", role: "Singer & Composer", img: "https://ui-avatars.com/api/?name=Sid+Sriram&background=random&size=200" }],
    reviews: [{ name: "Kavitha", rating: 5, comment: "His voice is truly otherworldly." }]
  },
  {
    title: "Anirudh Beats: Live Concert",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1429514513361-8fa32282fd5f?w=800",
    date: "2026-08-25T00:00:00Z",
    time: "6:30 PM",
    location: "MA Chidambaram Stadium, Chennai, Tamil Nadu",
    rating: "4.8",
    description: "Kollywood's hottest music composer Anirudh Ravichander performs his blockbuster tracks live — expect energy, dance, and pure euphoria.",
    price: 120000,
    organizer: "BookMyShow Live",
    features: ["General & VIP Zones", "LED Wristband", "Fan Pit"],
    crew: [{ name: "Anirudh Ravichander", role: "Music Composer & Performer", img: "https://ui-avatars.com/api/?name=Anirudh+Ravichander&background=random&size=200" }],
    reviews: [{ name: "Harish", rating: 5, comment: "The crowd was absolutely electric!" }]
  },
  {
    title: "Yuvan Shankar Raja Night",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-09-12T00:00:00Z",
    time: "7:00 PM",
    location: "SDAT Tennis Stadium, Chennai, Tamil Nadu",
    rating: "4.7",
    description: "Yuvan Shankar Raja — Tamil cinema's prince of melody — delivers an unforgettable live performance spanning two decades of iconic music.",
    price: 90000,
    organizer: "Percept Live",
    features: ["Reserved Seating", "Exclusive Merch", "Backstage Pass"],
    crew: [{ name: "Yuvan Shankar Raja", role: "Music Composer & Singer", img: "https://ui-avatars.com/api/?name=Yuvan+Shankar+Raja&background=random&size=200" }],
    reviews: [{ name: "Lalitha", rating: 5, comment: "Every song was a memory come alive." }]
  },
  {
    title: "D. Imman: Film Music Gala",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "6:00 PM",
    location: "Formans Stadium, Chennai, Tamil Nadu",
    rating: "4.6",
    description: "An evening of timeless film scores by D. Imman performed live with a 60-piece symphony orchestra. Experience Tamil cinema's most beloved melodies.",
    price: 85000,
    organizer: "Symphony Entertainment",
    features: ["Symphony Orchestra", "VIP Seating", "Programme Booklet"],
    crew: [{ name: "D. Imman", role: "Film Composer", img: "https://ui-avatars.com/api/?name=D+Imman&background=random&size=200" }],
    reviews: [{ name: "Padma", rating: 5, comment: "Classical yet cinematic — absolutely stunning." }]
  },

  // ── Tamil Nadu · Events (Arena) ──────────────────────────────────────────────
  {
    title: "VibePass Startup Expo Chennai",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    date: "2026-07-28T00:00:00Z",
    time: "9:00 AM",
    location: "TIDEL Park Arena, Chennai, Tamil Nadu",
    rating: "4.6",
    description: "South India's biggest startup expo — 200+ exhibitors, unicorn founder keynotes, live pitch battles, and premier networking sessions.",
    price: 50000,
    organizer: "VibePass Ventures",
    features: ["Investor Pitch Sessions", "Free Networking Lunch", "Startup Showcase"],
    crew: [{ name: "Anand Krishnan", role: "Event Director", img: "https://ui-avatars.com/api/?name=Anand+Krishnan&background=random&size=200" }],
    reviews: [{ name: "Rahul", rating: 5, comment: "Met my co-founder here. Life-changing event!" }]
  },
  {
    title: "Chennai Food & Culture Fest",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    date: "2026-08-10T00:00:00Z",
    time: "11:00 AM",
    location: "Island Grounds Arena, Chennai, Tamil Nadu",
    rating: "4.5",
    description: "A vibrant 3-day festival celebrating Tamil Nadu's culinary heritage — 100+ food stalls, live art, traditional dance and folk music performances.",
    price: 30000,
    organizer: "Chennai Events Corp",
    features: ["100+ Food Stalls", "Live Art", "Cultural Performances"],
    crew: [{ name: "Rema Suresh", role: "Festival Curator", img: "https://ui-avatars.com/api/?name=Rema+Suresh&background=random&size=200" }],
    reviews: [{ name: "Tarun", rating: 5, comment: "The chettinad food alone was worth it!" }]
  },
  {
    title: "IPL Fan Fest: CSK Edition",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    date: "2026-08-22T00:00:00Z",
    time: "3:00 PM",
    location: "Express Arena, Chennai, Tamil Nadu",
    rating: "4.8",
    description: "The ultimate CSK fan experience — live screenings, fan games, celebrity interactions, and the chance to meet your favourite players.",
    price: 55000,
    organizer: "CSK Fan Foundation",
    features: ["CSK Player Meet", "Live Match Screening", "CSK Merchandise"],
    crew: [{ name: "Vikram Anand", role: "Event Manager", img: "https://ui-avatars.com/api/?name=Vikram+Anand&background=random&size=200" }],
    reviews: [{ name: "Dhoni Fan", rating: 5, comment: "Yellove forever! Incredible atmosphere." }]
  },
  {
    title: "Tamil Nadu Coding Sprint",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
    date: "2026-09-15T00:00:00Z",
    time: "9:00 AM",
    location: "IIT Madras Research Arena, Chennai, Tamil Nadu",
    rating: "4.7",
    description: "A 48-hour hackathon with ₹25 lakh prize pool — 5000 developers, AI challenges, and mentorship sessions from top tech companies.",
    price: 20000,
    organizer: "IIT Madras Innovation Hub",
    features: ["₹25L Prize Pool", "Mentorship Sessions", "Cloud Credits"],
    crew: [{ name: "Prof. Ravi Kumar", role: "Hackathon Director", img: "https://ui-avatars.com/api/?name=Ravi+Kumar&background=random&size=200" }],
    reviews: [{ name: "Dev", rating: 5, comment: "Won my first hackathon here. Incredible!" }]
  },
  {
    title: "Pongal Sports & Heritage Carnival",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800",
    date: "2026-09-30T00:00:00Z",
    time: "8:00 AM",
    location: "Guindy Arena, Chennai, Tamil Nadu",
    rating: "4.6",
    description: "A vibrant Pongal-themed carnival featuring traditional sports (Jallikattu, Kabaddi), bull surfing exhibitions, and folk art performances.",
    price: 25000,
    organizer: "TN Heritage Trust",
    features: ["Traditional Sports", "Folk Art Expo", "Ethnic Food Zone"],
    crew: [{ name: "Selva Mani", role: "Carnival Director", img: "https://ui-avatars.com/api/?name=Selva+Mani&background=random&size=200" }],
    reviews: [{ name: "Nisha", rating: 5, comment: "Felt deeply connected to Tamil roots." }]
  },

  // ════════════════════════════════════════════════════════════════════════════
  //  KARNATAKA — 20 events
  // ════════════════════════════════════════════════════════════════════════════

  // ── Karnataka · Movies (Theatre) ─────────────────────────────────────────────
  {
    title: "Kalki 2898 AD",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    date: "2026-07-20T00:00:00Z",
    time: "Various Timings",
    location: "INOX Grand Theatre, Bengaluru, Karnataka",
    rating: "4.8",
    description: "A mythological sci-fi epic blending Kalki mythology with a futuristic dystopia. Starring Prabhas, Deepika Padukone, and Amitabh Bachchan.",
    price: 40000,
    organizer: "Vyjayanthi Movies",
    features: ["IMAX Experience", "Premium Seating", "Digital Surround Sound"],
    crew: [
      { name: "Nag Ashwin", role: "Director", img: "https://ui-avatars.com/api/?name=Nag+Ashwin&background=random&size=200" },
      { name: "Prabhas", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Prabhas&background=random&size=200" }
    ],
    reviews: [{ name: "Meera", rating: 5, comment: "Visually stunning! A cinematic masterpiece." }]
  },
  {
    title: "KGF Chapter 3",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800",
    date: "2026-08-15T00:00:00Z",
    time: "Various Timings",
    location: "PVR Phoenix Mall Theatre, Bengaluru, Karnataka",
    rating: "4.9",
    description: "Rocky's legacy continues in this explosive third installment of the Kolar Gold Fields saga. Yash returns with unmatched power and fury.",
    price: 45000,
    organizer: "Hombale Films",
    features: ["4K Laser Projection", "Luxury Recliners", "VIP Lounge"],
    crew: [
      { name: "Prashanth Neel", role: "Director", img: "https://ui-avatars.com/api/?name=Prashanth+Neel&background=random&size=200" },
      { name: "Yash", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Yash&background=random&size=200" }
    ],
    reviews: [{ name: "Kiran", rating: 5, comment: "Rocky Bhai is back and better than ever!" }]
  },
  {
    title: "Kantara 2",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800",
    date: "2026-08-28T00:00:00Z",
    time: "Various Timings",
    location: "Cinepolis Theatre, Bengaluru, Karnataka",
    rating: "4.8",
    description: "Rishab Shetty's spiritual sequel to the cultural phenomenon Kantara — deeper mythology, intense action, and a divine reckoning.",
    price: 42000,
    organizer: "Hombale Films",
    features: ["Dolby Atmos", "Director's Note Booklet", "Special Screening"],
    crew: [
      { name: "Rishab Shetty", role: "Director & Lead Actor", img: "https://ui-avatars.com/api/?name=Rishab+Shetty&background=random&size=200" }
    ],
    reviews: [{ name: "Suvarna", rating: 5, comment: "Even more powerful than the original!" }]
  },
  {
    title: "RRR Reloaded",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800",
    date: "2026-09-10T00:00:00Z",
    time: "Various Timings",
    location: "Innovative Multiplex Theatre, Bengaluru, Karnataka",
    rating: "4.9",
    description: "The director's cut of SS Rajamouli's global blockbuster RRR — 20 minutes of never-before-seen footage restored for the big screen.",
    price: 35000,
    organizer: "DVV Entertainment",
    features: ["Director's Cut", "Collectible Booklet", "Dolby Vision"],
    crew: [
      { name: "S.S. Rajamouli", role: "Director", img: "https://ui-avatars.com/api/?name=SS+Rajamouli&background=random&size=200" },
      { name: "Ram Charan", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Ram+Charan&background=random&size=200" }
    ],
    reviews: [{ name: "Priya", rating: 5, comment: "Best Indian film ever made. Naatu Naatu forever!" }]
  },
  {
    title: "777 Charlie Returns",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800",
    date: "2026-09-25T00:00:00Z",
    time: "Various Timings",
    location: "IMAX Theatre, Bengaluru, Karnataka",
    rating: "4.7",
    description: "Rakshit Shetty and the beloved dog Charlie reunite in a heartwarming sequel — a story about love, loss, and the healing power of friendship.",
    price: 32000,
    organizer: "Paramvah Studios",
    features: ["Pet-Friendly Premiere", "Charity Donation Screen", "Exclusive Merch"],
    crew: [
      { name: "Kiranraj K", role: "Director", img: "https://ui-avatars.com/api/?name=Kiranraj+K&background=random&size=200" },
      { name: "Rakshit Shetty", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Rakshit+Shetty&background=random&size=200" }
    ],
    reviews: [{ name: "Varsha", rating: 5, comment: "Cried happy tears for the entire second half." }]
  },

  // ── Karnataka · Shows (Hall) ──────────────────────────────────────────────────
  {
    title: "Kapil Sharma Comedy Night",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-07-25T00:00:00Z",
    time: "7:30 PM",
    location: "Ravindra Kalakshetra Hall, Bengaluru, Karnataka",
    rating: "4.7",
    description: "India's most beloved TV comedian brings his laugh riot live show to Bengaluru. Expect impromptu jokes and celebrity interactions.",
    price: 90000,
    organizer: "TalkFest Productions",
    features: ["VIP Seating", "Celebrity Surprise Guests", "Post-show Photo"],
    crew: [{ name: "Kapil Sharma", role: "Host & Comedian", img: "https://ui-avatars.com/api/?name=Kapil+Sharma&background=random&size=200" }],
    reviews: [{ name: "Deepak", rating: 5, comment: "He's even funnier in person!" }]
  },
  {
    title: "Kannada Drama Festival",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800",
    date: "2026-08-08T00:00:00Z",
    time: "6:30 PM",
    location: "Rangashankara Hall, Bengaluru, Karnataka",
    rating: "4.8",
    description: "Karnataka's premier dramatic arts festival showcasing award-winning Kannada plays, street theatre, and one-act performances over three evenings.",
    price: 55000,
    organizer: "Rangashankara Trust",
    features: ["Multi-Stage Format", "Artist Interaction", "Opening Night Gala"],
    crew: [{ name: "Arundhati Nag", role: "Artistic Director", img: "https://ui-avatars.com/api/?name=Arundhati+Nag&background=random&size=200" }],
    reviews: [{ name: "Poornima", rating: 5, comment: "Theatre that moved me to my core." }]
  },
  {
    title: "Bengaluru Comedy Club Showcase",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-08-22T00:00:00Z",
    time: "8:00 PM",
    location: "Chowdaiah Memorial Hall, Bengaluru, Karnataka",
    rating: "4.6",
    description: "Bengaluru's top stand-up comedians compete in a raucous showcase — find your next favourite comedian before they're famous.",
    price: 45000,
    organizer: "The Comedy Factory",
    features: ["10+ Comedians", "Open Bar", "Fan Voting"],
    crew: [{ name: "Kumar Comedy", role: "Host", img: "https://ui-avatars.com/api/?name=Kumar+Comedy&background=random&size=200" }],
    reviews: [{ name: "Ashok", rating: 5, comment: "Discovered three brilliant new voices!" }]
  },
  {
    title: "Yakshagana Dance Drama",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    date: "2026-09-07T00:00:00Z",
    time: "6:00 PM",
    location: "Gayana Samaja Hall, Bengaluru, Karnataka",
    rating: "4.9",
    description: "Karnataka's ancient folk theatre art Yakshagana performed by masters — vibrant costumes, mythological storytelling, and live percussion.",
    price: 40000,
    organizer: "Karnataka Yakshagana Academy",
    features: ["Costumed Performance", "Folk Music", "Pre-show Workshop"],
    crew: [{ name: "Sheni Gopalakrishna Bhat", role: "Senior Artiste", img: "https://ui-avatars.com/api/?name=Gopalkrishna+Bhat&background=random&size=200" }],
    reviews: [{ name: "Sunitha", rating: 5, comment: "A dying art kept beautifully alive." }]
  },
  {
    title: "Comicstaan Finalists Live",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    date: "2026-09-20T00:00:00Z",
    time: "7:00 PM",
    location: "Alliance Française Hall, Bengaluru, Karnataka",
    rating: "4.7",
    description: "Watch the top 6 finalists from Amazon Prime's Comicstaan Season 4 perform their best sets live — who'll win the crowd?",
    price: 65000,
    organizer: "Amazon Prime Video Live",
    features: ["6 Top Comedians", "Live Audience Voting", "Winner Crowned Live"],
    crew: [{ name: "Biswa Kalyan Rath", role: "Show Host", img: "https://ui-avatars.com/api/?name=Biswa+Kalyan+Rath&background=random&size=200" }],
    reviews: [{ name: "Nandita", rating: 5, comment: "Couldn't stop laughing for 3 hours!" }]
  },

  // ── Karnataka · Concerts (Stadium) ───────────────────────────────────────────
  {
    title: "Diljit Dosanjh Dil-Luminati",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    date: "2026-08-01T00:00:00Z",
    time: "7:00 PM",
    location: "M. Chinnaswamy Stadium, Bengaluru, Karnataka",
    rating: "4.9",
    description: "Diljit Dosanjh brings his blockbuster Dil-Luminati tour to Bengaluru — the biggest Punjabi pop concert in South India.",
    price: 120000,
    organizer: "BookMyShow Live",
    features: ["General & VIP Zones", "LED Wristband", "Fan Pit"],
    crew: [{ name: "Diljit Dosanjh", role: "Singer & Performer", img: "https://ui-avatars.com/api/?name=Diljit+Dosanjh&background=random&size=200" }],
    reviews: [{ name: "Harpreet", rating: 5, comment: "The energy was insane!" }]
  },
  {
    title: "Sonu Nigam Live",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1429514513361-8fa32282fd5f?w=800",
    date: "2026-08-18T00:00:00Z",
    time: "7:00 PM",
    location: "Kanteerava Stadium, Bengaluru, Karnataka",
    rating: "4.8",
    description: "The golden voice of Bollywood performs his greatest hits spanning 30 years — classic film songs, ghazals, and soulful renditions.",
    price: 110000,
    organizer: "Percept Live",
    features: ["Reserved Seating", "Full Band", "VIP Hospitality"],
    crew: [{ name: "Sonu Nigam", role: "Singer", img: "https://ui-avatars.com/api/?name=Sonu+Nigam&background=random&size=200" }],
    reviews: [{ name: "Geeta", rating: 5, comment: "His voice still gives me chills after all these years." }]
  },
  {
    title: "Ilaiyaraaja Symphony",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800",
    date: "2026-09-03T00:00:00Z",
    time: "6:00 PM",
    location: "Sree Kanteerava Outdoor Stadium, Bengaluru, Karnataka",
    rating: "5.0",
    description: "A grand symphonic tribute to Maestro Ilaiyaraaja — 100 orchestral musicians perform his timeless classics from Tamil, Telugu, and Kannada cinema.",
    price: 130000,
    organizer: "Symphony Trust",
    features: ["100-piece Orchestra", "Golden Circle VIP", "Maestro Tribute Video"],
    crew: [{ name: "Ilaiyaraaja", role: "Composer & Conductor", img: "https://ui-avatars.com/api/?name=Ilaiyaraaja&background=random&size=200" }],
    reviews: [{ name: "Lakshman", rating: 5, comment: "When the orchestra played Roja — I wept." }]
  },
  {
    title: "Nucleya Bass Drop Live",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-09-17T00:00:00Z",
    time: "8:00 PM",
    location: "Palace Grounds Stadium, Bengaluru, Karnataka",
    rating: "4.7",
    description: "India's electronic music king Nucleya delivers an explosive bass-heavy live show with cutting-edge stage production and Indian folk fusion.",
    price: 95000,
    organizer: "Vh1 Supersonic",
    features: ["LED Stage Production", "VIP Dance Floor", "Merch Exclusive"],
    crew: [{ name: "Nucleya", role: "DJ & Musician", img: "https://ui-avatars.com/api/?name=Nucleya&background=random&size=200" }],
    reviews: [{ name: "Rohan", rating: 5, comment: "The bass literally moved my soul." }]
  },
  {
    title: "Shankar Ehsaan Loy Reunion",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "7:00 PM",
    location: "GKVK Stadium, Bengaluru, Karnataka",
    rating: "4.8",
    description: "The legendary trio Shankar-Ehsaan-Loy performs a reunion concert spanning their iconic Bollywood and world music collaborations.",
    price: 105000,
    organizer: "Quintessentially India",
    features: ["Full Band Setup", "Duo Medley Segments", "VIP Backstage"],
    crew: [
      { name: "Shankar Mahadevan", role: "Singer & Composer", img: "https://ui-avatars.com/api/?name=Shankar+Mahadevan&background=random&size=200" },
      { name: "Ehsaan Noorani", role: "Guitarist", img: "https://ui-avatars.com/api/?name=Ehsaan+Noorani&background=random&size=200" }
    ],
    reviews: [{ name: "Vijay", rating: 5, comment: "When they played Breathless live — perfection." }]
  },

  // ── Karnataka · Events (Arena) ────────────────────────────────────────────────
  {
    title: "Bengaluru Tech Summit 2026",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
    date: "2026-08-08T00:00:00Z",
    time: "9:30 AM",
    location: "KTPO Arena, Bengaluru, Karnataka",
    rating: "4.8",
    description: "Asia's premier technology summit — global tech leaders, policymakers, and innovators discussing the future of AI, deeptech, and digital transformation.",
    price: 75000,
    organizer: "Government of Karnataka",
    features: ["Global Speaker Lineup", "Workshop Sessions", "Exhibition Hall"],
    crew: [{ name: "Dr. Priya Menon", role: "Conference Chair", img: "https://ui-avatars.com/api/?name=Priya+Menon&background=random&size=200" }],
    reviews: [{ name: "Vikram", rating: 5, comment: "Best tech event in Asia bar none." }]
  },
  {
    title: "Namma Bengaluru Marathon",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800",
    date: "2026-08-25T00:00:00Z",
    time: "5:30 AM",
    location: "Cubbon Park Arena, Bengaluru, Karnataka",
    rating: "4.7",
    description: "Bengaluru's iconic annual marathon through the Garden City — 42K full marathon, 21K half, and 10K fun run routes through heritage boulevards.",
    price: 30000,
    organizer: "Procam International",
    features: ["Finisher Medal", "Timing Chip", "Post-race Recovery Zone"],
    crew: [{ name: "Arun Bhatt", role: "Race Director", img: "https://ui-avatars.com/api/?name=Arun+Bhatt&background=random&size=200" }],
    reviews: [{ name: "Preethi", rating: 5, comment: "Running through Cubbon Park at dawn is magical." }]
  },
  {
    title: "Game Developers Conference India",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    date: "2026-09-06T00:00:00Z",
    time: "10:00 AM",
    location: "Bengaluru International Arena, Bengaluru, Karnataka",
    rating: "4.6",
    description: "India's largest gaming industry conference — indie game showcases, AAA studio panels, esports tournaments, and live game demos.",
    price: 60000,
    organizer: "NASSCOM",
    features: ["Game Showcase", "Esports Tournament", "Industry Panels"],
    crew: [{ name: "Rajesh Kumar", role: "Event Producer", img: "https://ui-avatars.com/api/?name=Rajesh+Kumar&background=random&size=200" }],
    reviews: [{ name: "Dev Gamer", rating: 5, comment: "Best gaming event in South Asia!" }]
  },
  {
    title: "Dasara Cultural Carnival",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    date: "2026-09-20T00:00:00Z",
    time: "10:00 AM",
    location: "Mysore Palace Arena, Bengaluru, Karnataka",
    rating: "4.9",
    description: "Karnataka's iconic Dasara festival transformed into a grand cultural carnival — processions, folk dances, classical music, and illuminated palace spectacle.",
    price: 35000,
    organizer: "Karnataka State Tourism",
    features: ["Palace Illumination", "Elephant Procession", "Cultural Performances"],
    crew: [{ name: "Shankar Rao", role: "Festival Director", img: "https://ui-avatars.com/api/?name=Shankar+Rao&background=random&size=200" }],
    reviews: [{ name: "Devika", rating: 5, comment: "The palace lit up at night was breathtaking." }]
  },
  {
    title: "Garden City Flower Show",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "9:00 AM",
    location: "Lalbagh Arena, Bengaluru, Karnataka",
    rating: "4.5",
    description: "Lalbagh Botanical Garden's annual flower show — millions of blooms, horticultural competitions, and live plant art installations across 240 acres.",
    price: 20000,
    organizer: "Horticulture Dept Karnataka",
    features: ["Million Blooms Display", "Plant Market", "Guided Tours"],
    crew: [{ name: "Dr. M.J. Hegde", role: "Chief Botanist", img: "https://ui-avatars.com/api/?name=MJ+Hegde&background=random&size=200" }],
    reviews: [{ name: "Girija", rating: 5, comment: "A feast for the eyes every single visit." }]
  },

  // ════════════════════════════════════════════════════════════════════════════
  //  ANDHRA PRADESH — 20 events
  // ════════════════════════════════════════════════════════════════════════════

  // ── Andhra Pradesh · Movies (Theatre) ────────────────────────────────────────
  {
    title: "Pushpa 2: The Rule",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800",
    date: "2026-08-05T00:00:00Z",
    time: "Various Timings",
    location: "Cinepolis Luxe Theatre, Hyderabad, Andhra Pradesh",
    rating: "4.7",
    description: "Allu Arjun returns as Pushpa Raj in the explosive sequel. The red sandalwood smuggler faces even deadlier enemies as he battles to rule the underworld.",
    price: 38000,
    organizer: "Mythri Movie Makers",
    features: ["4DX Seating", "Recliner Zone", "Snack Combo Included"],
    crew: [
      { name: "Sukumar", role: "Director", img: "https://ui-avatars.com/api/?name=Sukumar&background=random&size=200" },
      { name: "Allu Arjun", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Allu+Arjun&background=random&size=200" }
    ],
    reviews: [{ name: "Ravi", rating: 5, comment: "Allu Arjun is phenomenal!" }]
  },
  {
    title: "Mahesh Babu 30",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    date: "2026-08-20T00:00:00Z",
    time: "Various Timings",
    location: "Prasads IMAX Theatre, Hyderabad, Andhra Pradesh",
    rating: "4.8",
    description: "Mahesh Babu's milestone 30th film — a global action-spy thriller directed by SS Rajamouli, shot across 10 countries.",
    price: 50000,
    organizer: "G. Mahesh Babu Entertainment",
    features: ["IMAX Experience", "World Premiere", "Director's Cut Edition"],
    crew: [
      { name: "S.S. Rajamouli", role: "Director", img: "https://ui-avatars.com/api/?name=SS+Rajamouli&background=random&size=200" },
      { name: "Mahesh Babu", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Mahesh+Babu&background=random&size=200" }
    ],
    reviews: [{ name: "Suresh", rating: 5, comment: "Rajamouli + Mahesh = absolute perfection!" }]
  },
  {
    title: "Balakrishna 109",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800",
    date: "2026-09-01T00:00:00Z",
    time: "Various Timings",
    location: "AMB Cinemas Theatre, Hyderabad, Andhra Pradesh",
    rating: "4.6",
    description: "Nandamuri Balakrishna celebrates his 109th film with a mass masala entertainer in the grand NTR tradition — action, drama, and powerful dialogues.",
    price: 35000,
    organizer: "Sri Venkateswara Cine Chitra",
    features: ["Mass Entertainment", "Balayya Dialogue Remix", "Special Fan Show"],
    crew: [
      { name: "Anil Ravipudi", role: "Director", img: "https://ui-avatars.com/api/?name=Anil+Ravipudi&background=random&size=200" },
      { name: "Balakrishna", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Balakrishna&background=random&size=200" }
    ],
    reviews: [{ name: "Swamy", rating: 5, comment: "Mass maharaja at his thunderous best!" }]
  },
  {
    title: "Pawan Kalyan Power Star",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800",
    date: "2026-09-15T00:00:00Z",
    time: "Various Timings",
    location: "Asian Multiplex Theatre, Hyderabad, Andhra Pradesh",
    rating: "4.8",
    description: "Before Pawan Kalyan fully entered politics, this was his farewell film — now re-releasing with extended scenes and a powerful message.",
    price: 40000,
    organizer: "Vakeel Saab Productions",
    features: ["Extended Edition", "Fan Meet Event", "Special BGM Concert"],
    crew: [
      { name: "Trivikram Srinivas", role: "Director", img: "https://ui-avatars.com/api/?name=Trivikram+Srinivas&background=random&size=200" },
      { name: "Pawan Kalyan", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Pawan+Kalyan&background=random&size=200" }
    ],
    reviews: [{ name: "Bhavani", rating: 5, comment: "Power Star's swansong is a masterpiece." }]
  },
  {
    title: "Ram Charan Mega Blockbuster",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "Various Timings",
    location: "Devi 70MM Theatre, Hyderabad, Andhra Pradesh",
    rating: "4.7",
    description: "Ram Charan's solo action epic — post-RRR global stardom meets a deeply personal Telugu story about identity, honor, and sacrifice.",
    price: 42000,
    organizer: "Konidela Production Company",
    features: ["Global Premiere", "Mega Family Interaction", "VIP Fan Experience"],
    crew: [
      { name: "Shankar", role: "Director", img: "https://ui-avatars.com/api/?name=Shankar&background=random&size=200" },
      { name: "Ram Charan", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Ram+Charan&background=random&size=200" }
    ],
    reviews: [{ name: "Naga", rating: 5, comment: "Shankar + Ram Charan = 💥 unbeatable!" }]
  },

  // ── Andhra Pradesh · Shows (Hall) ─────────────────────────────────────────────
  {
    title: "Kiraak Comedy Show",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-08-10T00:00:00Z",
    time: "6:30 PM",
    location: "Ravindra Bharathi Hall, Hyderabad, Andhra Pradesh",
    rating: "4.6",
    description: "Telugu's biggest comedy troupe brings their best sketches, mimicry acts, and improvisational humour in a 3-hour comedy bonanza.",
    price: 60000,
    organizer: "Kiraak Productions",
    features: ["Assigned Seating", "Snack Hamper", "Raffle Prizes"],
    crew: [
      { name: "Sudigali Sudheer", role: "Lead Comedian", img: "https://ui-avatars.com/api/?name=Sudigali+Sudheer&background=random&size=200" },
      { name: "Auto Ram Prasad", role: "Comedian", img: "https://ui-avatars.com/api/?name=Auto+Ram+Prasad&background=random&size=200" }
    ],
    reviews: [{ name: "Sravya", rating: 5, comment: "Best comedy show in Hyderabad!" }]
  },
  {
    title: "Telangana Cultural Drama Night",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800",
    date: "2026-08-22T00:00:00Z",
    time: "7:00 PM",
    location: "Taramati Baradari Hall, Hyderabad, Andhra Pradesh",
    rating: "4.7",
    description: "A powerful evening of Telangana folk drama, Burrakatha storytelling, and Perini dance — celebrating the state's rich artistic traditions.",
    price: 50000,
    organizer: "Telangana Arts Council",
    features: ["Folk Art Exhibition", "Traditional Costumes", "Supper Included"],
    crew: [{ name: "Vijaya Lakshmi", role: "Artistic Director", img: "https://ui-avatars.com/api/?name=Vijaya+Lakshmi&background=random&size=200" }],
    reviews: [{ name: "Padmavati", rating: 5, comment: "The Burrakatha was mesmerizing." }]
  },
  {
    title: "Hyderabad Nawabi Mushaira",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    date: "2026-09-06T00:00:00Z",
    time: "7:30 PM",
    location: "Chowmahalla Palace Hall, Hyderabad, Andhra Pradesh",
    rating: "4.8",
    description: "A royal Mushaira (Urdu poetry gathering) in the regal setting of Chowmahalla Palace — celebrated poets, ghazals, and nazms in Hyderabad's finest tradition.",
    price: 70000,
    organizer: "Hyderabad Heritage Foundation",
    features: ["Palace Setting", "Dum Biryani Dinner", "Collector's Poetry Book"],
    crew: [{ name: "Wasim Barelvi", role: "Senior Poet", img: "https://ui-avatars.com/api/?name=Wasim+Barelvi&background=random&size=200" }],
    reviews: [{ name: "Javed", rating: 5, comment: "Poetry in a palace — as royal as it gets." }]
  },
  {
    title: "Telugu Comedy Superleague",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    date: "2026-09-18T00:00:00Z",
    time: "7:00 PM",
    location: "Lalitha Kala Thoranam Hall, Hyderabad, Andhra Pradesh",
    rating: "4.5",
    description: "Eight top Telugu stand-up comedians compete in a head-to-head comedy league — audience votes determine the champion each night.",
    price: 55000,
    organizer: "Telugu Talkies",
    features: ["8-Comedian Lineup", "Audience Voting", "Championship Trophy Night"],
    crew: [{ name: "Srikanth Reddy", role: "Showrunner", img: "https://ui-avatars.com/api/?name=Srikanth+Reddy&background=random&size=200" }],
    reviews: [{ name: "Kaveri", rating: 5, comment: "Voted for my favourite 6 times in a row!" }]
  },
  {
    title: "Andhra Puppet Theatre Festival",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "5:00 PM",
    location: "Andhra Pradesh State Academy Hall, Hyderabad, Andhra Pradesh",
    rating: "4.9",
    description: "The dying art of Tholu Bommalata (shadow puppetry) is celebrated in this unique festival showcasing master puppeteers from across the state.",
    price: 35000,
    organizer: "AP Cultural Heritage Trust",
    features: ["Shadow Puppet Shows", "Craft Workshop", "Children's Matinee"],
    crew: [{ name: "Singanapalli Obanna", role: "Master Puppeteer", img: "https://ui-avatars.com/api/?name=Singanapalli+Obanna&background=random&size=200" }],
    reviews: [{ name: "Haritha", rating: 5, comment: "My children were completely spellbound." }]
  },

  // ── Andhra Pradesh · Concerts (Stadium) ──────────────────────────────────────
  {
    title: "Sid Sriram Soul Concert",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-08-18T00:00:00Z",
    time: "6:30 PM",
    location: "Rajiv Gandhi International Cricket Stadium, Hyderabad, Andhra Pradesh",
    rating: "4.8",
    description: "Sid Sriram performs his iconic Telugu and Tamil songs live with a full band, ambient light shows, and intimate acoustic moments.",
    price: 95000,
    organizer: "Qube Concerts",
    features: ["Reserved Seating", "Acoustic Zone", "Artist Signed Poster"],
    crew: [{ name: "Sid Sriram", role: "Singer & Composer", img: "https://ui-avatars.com/api/?name=Sid+Sriram&background=random&size=200" }],
    reviews: [{ name: "Kavitha", rating: 5, comment: "His voice is truly otherworldly." }]
  },
  {
    title: "DSP Thaman Live",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    date: "2026-08-30T00:00:00Z",
    time: "7:00 PM",
    location: "LB Stadium, Hyderabad, Andhra Pradesh",
    rating: "4.7",
    description: "Telugu cinema's dynamic music duo DSP and Thaman S perform their chart-topping compositions back to back in an electrifying stadium experience.",
    price: 100000,
    organizer: "Aha Entertainment",
    features: ["LED Stage Production", "VIP Fan Zone", "Photo Opportunity"],
    crew: [
      { name: "Devi Sri Prasad", role: "Music Composer", img: "https://ui-avatars.com/api/?name=Devi+Sri+Prasad&background=random&size=200" },
      { name: "S. Thaman", role: "Music Composer", img: "https://ui-avatars.com/api/?name=S+Thaman&background=random&size=200" }
    ],
    reviews: [{ name: "Vijay", rating: 5, comment: "The DSP-Thaman collab was out of this world!" }]
  },
  {
    title: "Udit Narayan Evergreen Night",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800",
    date: "2026-09-12T00:00:00Z",
    time: "6:00 PM",
    location: "Gachibowli Stadium, Hyderabad, Andhra Pradesh",
    rating: "4.6",
    description: "Udit Narayan performs 4 decades of Bollywood's most beloved songs — a nostalgic journey through Hindi cinema's golden era.",
    price: 85000,
    organizer: "SoundWave Concerts",
    features: ["Full Band", "Nostalgia Wall", "Dedicated Decades Segment"],
    crew: [{ name: "Udit Narayan", role: "Singer", img: "https://ui-avatars.com/api/?name=Udit+Narayan&background=random&size=200" }],
    reviews: [{ name: "Asha", rating: 5, comment: "Took me back to my teenage years instantly." }]
  },
  {
    title: "Karthik King Live",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1429514513361-8fa32282fd5f?w=800",
    date: "2026-09-22T00:00:00Z",
    time: "7:30 PM",
    location: "Indoor Cricket Stadium, Hyderabad, Andhra Pradesh",
    rating: "4.7",
    description: "Karthik (the King), with his unmistakable falsetto and energy, delivers a career-spanning concert from Tamil hit to Telugu blockbuster.",
    price: 90000,
    organizer: "Mango Music Events",
    features: ["Fan Interaction Segment", "Sing-Along Zone", "Golden Tickets"],
    crew: [{ name: "Karthik", role: "Singer", img: "https://ui-avatars.com/api/?name=Karthik+Singer&background=random&size=200" }],
    reviews: [{ name: "Sundar", rating: 5, comment: "The falsetto notes made the stadium go crazy!" }]
  },
  {
    title: "MM Keeravani Classical Night",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-09-30T00:00:00Z",
    time: "6:00 PM",
    location: "Hitex Stadium, Hyderabad, Andhra Pradesh",
    rating: "4.9",
    description: "Oscar-winning MM Keeravani performs his classical compositions and film scores live — from Baahubali to Naatu Naatu in a magical stadium night.",
    price: 115000,
    organizer: "Tollywood Music Events",
    features: ["Orchestra Setup", "Oscar Tribute Segment", "VIP Hospitality Suite"],
    crew: [{ name: "M.M. Keeravani", role: "Composer & Conductor", img: "https://ui-avatars.com/api/?name=MM+Keeravani&background=random&size=200" }],
    reviews: [{ name: "Ramesh", rating: 5, comment: "An Oscar winner conducting his own music live!" }]
  },

  // ── Andhra Pradesh · Events (Arena) ───────────────────────────────────────────
  {
    title: "Hyderabad Food & Culture Carnival",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    date: "2026-08-25T00:00:00Z",
    time: "11:00 AM",
    location: "Hitex Exhibition Arena, Hyderabad, Andhra Pradesh",
    rating: "4.5",
    description: "A vibrant 3-day festival celebrating Hyderabad's culinary heritage — 100+ food stalls, live art installations, and cultural performances.",
    price: 30000,
    organizer: "Hyderabad Events Corp",
    features: ["100+ Food Stalls", "Live Art Installations", "Cultural Performances"],
    crew: [{ name: "Shahnaz Ahmed", role: "Festival Curator", img: "https://ui-avatars.com/api/?name=Shahnaz+Ahmed&background=random&size=200" }],
    reviews: [{ name: "Tarun", rating: 5, comment: "The biryani alone was worth the ticket price!" }]
  },
  {
    title: "Deccan Drone Racing Championship",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
    date: "2026-09-05T00:00:00Z",
    time: "10:00 AM",
    location: "HICC Arena, Hyderabad, Andhra Pradesh",
    rating: "4.6",
    description: "South India's first professional drone racing championship — 100+ pilots, obstacle courses, and FPV live feeds on giant screens.",
    price: 40000,
    organizer: "Drone Sports India",
    features: ["FPV Live Screens", "Pilot Meet & Greet", "Open Practice Laps"],
    crew: [{ name: "Kiran Sagar", role: "Race Coordinator", img: "https://ui-avatars.com/api/?name=Kiran+Sagar&background=random&size=200" }],
    reviews: [{ name: "Rohan", rating: 5, comment: "The speed of these drones is insane!" }]
  },
  {
    title: "Andhra Heritage Expo",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    date: "2026-09-15T00:00:00Z",
    time: "10:00 AM",
    location: "BIEC Arena, Hyderabad, Andhra Pradesh",
    rating: "4.5",
    description: "A comprehensive exhibition celebrating Andhra Pradesh's art, crafts, weaving traditions, cuisine, and classical dance forms across 300+ stalls.",
    price: 25000,
    organizer: "AP Tourism",
    features: ["300+ Artisan Stalls", "Kalamkari Workshops", "Live Kuchipudi Dance"],
    crew: [{ name: "Anitha Reddy", role: "Heritage Curator", img: "https://ui-avatars.com/api/?name=Anitha+Reddy&background=random&size=200" }],
    reviews: [{ name: "Savitha", rating: 5, comment: "Discovered incredible Kondapalli toys!" }]
  },
  {
    title: "Hyderabad Lit Fest",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    date: "2026-09-22T00:00:00Z",
    time: "9:00 AM",
    location: "Salar Jung Arena, Hyderabad, Andhra Pradesh",
    rating: "4.7",
    description: "The premier literary festival of the Deccan — 200+ authors, translators, historians, and poets discussing literature, language, and ideas.",
    price: 35000,
    organizer: "Hyderabad Literary Foundation",
    features: ["200+ Authors", "Book Signings", "Poetry Slam Finals"],
    crew: [{ name: "Anuradha Roy", role: "Festival Curator", img: "https://ui-avatars.com/api/?name=Anuradha+Roy&background=random&size=200" }],
    reviews: [{ name: "Lakshmi", rating: 5, comment: "Every session was a masterclass in ideas." }]
  },
  {
    title: "AP Chefs Cookout Championship",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800",
    date: "2026-09-30T00:00:00Z",
    time: "11:00 AM",
    location: "Novotel Arena, Hyderabad, Andhra Pradesh",
    rating: "4.6",
    description: "Andhra Pradesh's top chefs battle it out in the region's biggest culinary championship — Biryani Masterclass, Pesarattu challenges, and Gongura cook-offs.",
    price: 45000,
    organizer: "Hotel Association of AP",
    features: ["Live Cooking Battles", "Celebrity Chef Judges", "Tasting Experience"],
    crew: [{ name: "Chef Srikanth", role: "Head Judge", img: "https://ui-avatars.com/api/?name=Chef+Srikanth&background=random&size=200" }],
    reviews: [{ name: "Mamata", rating: 5, comment: "The biryani I tasted was life-changing." }]
  },

  // ════════════════════════════════════════════════════════════════════════════
  //  KERALA — 20 events
  // ════════════════════════════════════════════════════════════════════════════

  // ── Kerala · Movies (Theatre) ─────────────────────────────────────────────────
  {
    title: "RRR Reloaded — Kerala Premiere",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800",
    date: "2026-08-14T00:00:00Z",
    time: "Various Timings",
    location: "SPI Palazzo Theatre, Kochi, Kerala",
    rating: "4.9",
    description: "SS Rajamouli's global blockbuster RRR returns in director's cut with 20 minutes of exclusive footage — premiere showing in Kerala.",
    price: 32000,
    organizer: "DVV Entertainment",
    features: ["Director's Cut", "Collectible Booklet", "Dolby Vision"],
    crew: [
      { name: "S.S. Rajamouli", role: "Director", img: "https://ui-avatars.com/api/?name=SS+Rajamouli&background=random&size=200" },
      { name: "Ram Charan", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Ram+Charan&background=random&size=200" }
    ],
    reviews: [{ name: "Priya", rating: 5, comment: "Best Indian film ever made. Naatu Naatu forever!" }]
  },
  {
    title: "Lucifer 3",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800",
    date: "2026-08-28T00:00:00Z",
    time: "Various Timings",
    location: "Padma Theatre, Kochi, Kerala",
    rating: "4.8",
    description: "Mohanlal reprises his iconic Stephen Nedumpally role in the third chapter of Prithviraj's political thriller franchise — darker, deeper, deadlier.",
    price: 38000,
    organizer: "Antony Perumbavoor Productions",
    features: ["Premiere Night", "Advance Fan Show", "Special VFX Preview"],
    crew: [
      { name: "Prithviraj Sukumaran", role: "Director", img: "https://ui-avatars.com/api/?name=Prithviraj+Sukumaran&background=random&size=200" },
      { name: "Mohanlal", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Mohanlal&background=random&size=200" }
    ],
    reviews: [{ name: "Suresh", rating: 5, comment: "Mohanlal's screen presence is beyond description." }]
  },
  {
    title: "Mammootty's 400th Film",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    date: "2026-09-05T00:00:00Z",
    time: "Various Timings",
    location: "Carnival Cinemas Theatre, Thrissur, Kerala",
    rating: "4.7",
    description: "Megastar Mammootty celebrates his 400th film — a sweeping period drama spanning three eras of Kerala's history with stunning visuals.",
    price: 35000,
    organizer: "Mammootty Kampany",
    features: ["Grand Premiere", "400 Film Retrospective Screen", "Fan Night"],
    crew: [
      { name: "Martin Prakkat", role: "Director", img: "https://ui-avatars.com/api/?name=Martin+Prakkat&background=random&size=200" },
      { name: "Mammootty", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Mammootty&background=random&size=200" }
    ],
    reviews: [{ name: "Joseph", rating: 5, comment: "400 films and still the benchmark!" }]
  },
  {
    title: "Fahadh Faasil Noir",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800",
    date: "2026-09-18T00:00:00Z",
    time: "Various Timings",
    location: "Cinepolis Theatre, Kozhikode, Kerala",
    rating: "4.9",
    description: "Fahadh Faasil stars in a psychological noir thriller — a layered, cerebral film that challenges the boundaries of Malayalam cinema.",
    price: 30000,
    organizer: "Friday Film House",
    features: ["Award Screening", "Director Q&A", "Limited Edition Poster"],
    crew: [
      { name: "Dileesh Pothan", role: "Director", img: "https://ui-avatars.com/api/?name=Dileesh+Pothan&background=random&size=200" },
      { name: "Fahadh Faasil", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Fahadh+Faasil&background=random&size=200" }
    ],
    reviews: [{ name: "Aravind", rating: 5, comment: "Fahadh is simply in a league of his own." }]
  },
  {
    title: "Nivin Pauly: Mayaanadhi 2",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "Various Timings",
    location: "Gold Village Theatre, Thiruvananthapuram, Kerala",
    rating: "4.6",
    description: "The long-awaited sequel to the critically acclaimed Mayaanadhi — Appu and Aisha's story continues against the backdrop of Kerala's changing landscape.",
    price: 28000,
    organizer: "Anto Joseph Film Company",
    features: ["Reunion Premiere", "Behind-the-scenes Reel", "Director's Commentary"],
    crew: [
      { name: "Aashiq Abu", role: "Director", img: "https://ui-avatars.com/api/?name=Aashiq+Abu&background=random&size=200" },
      { name: "Nivin Pauly", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Nivin+Pauly&background=random&size=200" }
    ],
    reviews: [{ name: "Sona", rating: 5, comment: "As poetic and haunting as the first." }]
  },

  // ── Kerala · Shows (Hall) ─────────────────────────────────────────────────────
  {
    title: "Mugen Rao Musical Drama",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    date: "2026-08-22T00:00:00Z",
    time: "7:00 PM",
    location: "Town Hall Auditorium, Kochi, Kerala",
    rating: "4.7",
    description: "Mugen Rao presents a bilingual musical drama fusing Tamil and English compositions in a theatrical setting with live band accompaniment.",
    price: 70000,
    organizer: "Mugen Music Productions",
    features: ["VIP Seats", "Digital Programme", "Backstage Access"],
    crew: [{ name: "Mugen Rao", role: "Performer & Director", img: "https://ui-avatars.com/api/?name=Mugen+Rao&background=random&size=200" }],
    reviews: [{ name: "Pooja", rating: 5, comment: "An emotional and magical evening." }]
  },
  {
    title: "Kathakali Masters Performance",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800",
    date: "2026-09-03T00:00:00Z",
    time: "6:00 PM",
    location: "Kerala Kalamandalam Hall, Thrissur, Kerala",
    rating: "4.9",
    description: "Grand Masters of Kathakali perform three classical episodes live — Mahabharata stories brought to life through elaborate makeup, costume, and gesture.",
    price: 60000,
    organizer: "Kerala Kalamandalam",
    features: ["Makeup Demonstration", "Programme Booklet", "Heritage Venue"],
    crew: [
      { name: "Kalamandalam Gopi", role: "Kathakali Master", img: "https://ui-avatars.com/api/?name=Kalamandalam+Gopi&background=random&size=200" }
    ],
    reviews: [{ name: "Unni", rating: 5, comment: "A 600-year-old tradition brought to life magnificently." }]
  },
  {
    title: "Kairali Comedy Nights",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-09-14T00:00:00Z",
    time: "7:30 PM",
    location: "YMCA Hall, Kozhikode, Kerala",
    rating: "4.6",
    description: "Kerala's most popular stand-up comedians and mimicry artists perform together in a night of distinctly Malayali humour and pop-culture comedy.",
    price: 50000,
    organizer: "Kairali TV Events",
    features: ["10+ Performers", "Mimicry Segment", "Fan Q&A"],
    crew: [{ name: "Suraj Venjaramood", role: "Host & Comedian", img: "https://ui-avatars.com/api/?name=Suraj+Venjaramood&background=random&size=200" }],
    reviews: [{ name: "Aneesh", rating: 5, comment: "Suraj sir had us rolling on the floor!" }]
  },
  {
    title: "Mohiniyattam Dance Evening",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    date: "2026-09-22T00:00:00Z",
    time: "6:30 PM",
    location: "Tagore Hall, Thiruvananthapuram, Kerala",
    rating: "4.8",
    description: "An evening dedicated to Mohiniyattam — Kerala's feminine classical dance form. Three accomplished performers present solo and ensemble recitals.",
    price: 45000,
    organizer: "Sangeet Natak Akademi",
    features: ["Solo Recitals", "Ensemble Finale", "Meet the Artists"],
    crew: [{ name: "Pallavi Krishnan", role: "Lead Dancer", img: "https://ui-avatars.com/api/?name=Pallavi+Krishnan&background=random&size=200" }],
    reviews: [{ name: "Mrinalini", rating: 5, comment: "Graceful, powerful, and deeply moving." }]
  },
  {
    title: "Onam Heritage Drama Festival",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-09-30T00:00:00Z",
    time: "5:00 PM",
    location: "Poomala Cultural Hall, Thrissur, Kerala",
    rating: "4.7",
    description: "An Onam special drama festival presenting folk plays, Kummattikali mask dances, and Thiruvathirakali group performances across three stages.",
    price: 40000,
    organizer: "Kerala Festival Committee",
    features: ["Multi-Stage Format", "Traditional Sadya", "Pookalam Competition"],
    crew: [{ name: "Anoop Menon", role: "Festival Director", img: "https://ui-avatars.com/api/?name=Anoop+Menon&background=random&size=200" }],
    reviews: [{ name: "Kavya", rating: 5, comment: "The best Onam celebration I've ever attended!" }]
  },

  // ── Kerala · Concerts (Stadium) ───────────────────────────────────────────────
  {
    title: "Shankar Mahadevan Fusion Night",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-09-10T00:00:00Z",
    time: "6:00 PM",
    location: "Jawaharlal Nehru International Stadium, Kochi, Kerala",
    rating: "4.7",
    description: "Shankar Mahadevan performs a breath-taking fusion of classical Carnatic, Bollywood, and jazz in a unique stadium concert format.",
    price: 100000,
    organizer: "Percept Live",
    features: ["Fusion Orchestra", "Backstage Tour", "Exclusive Merchandise"],
    crew: [{ name: "Shankar Mahadevan", role: "Vocalist & Composer", img: "https://ui-avatars.com/api/?name=Shankar+Mahadevan&background=random&size=200" }],
    reviews: [{ name: "Ranjith", rating: 5, comment: "A perfect blend of tradition and modernity." }]
  },
  {
    title: "KS Chithra Golden Voice Live",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800",
    date: "2026-09-20T00:00:00Z",
    time: "6:30 PM",
    location: "GMC Balayogi Indoor Stadium, Kochi, Kerala",
    rating: "5.0",
    description: "The nightingale of South India, K.S. Chithra, performs 50 years of her most beloved Malayalam, Tamil, and Hindi songs in a golden anniversary concert.",
    price: 95000,
    organizer: "Sunday Concerts",
    features: ["Golden Anniversary Show", "50-Year Retrospective", "VIP Golden Seats"],
    crew: [{ name: "K.S. Chithra", role: "Singer", img: "https://ui-avatars.com/api/?name=KS+Chithra&background=random&size=200" }],
    reviews: [{ name: "Radha", rating: 5, comment: "The living legend brought tears to every eye." }]
  },
  {
    title: "Vineeth Sreenivasan Acoustic",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "7:00 PM",
    location: "Nehru Trophy Boat Race Stadium, Kottayam, Kerala",
    rating: "4.8",
    description: "Vineeth Sreenivasan — actor, director, and singer — performs an intimate acoustic show of his most loved Malayalam songs with guitar and piano.",
    price: 75000,
    organizer: "Friday Film House",
    features: ["Intimate Acoustic Show", "Fan Story Segment", "Candlelight Setting"],
    crew: [{ name: "Vineeth Sreenivasan", role: "Singer & Multi-Talent", img: "https://ui-avatars.com/api/?name=Vineeth+Sreenivasan&background=random&size=200" }],
    reviews: [{ name: "Anisha", rating: 5, comment: "Felt like a private concert in my living room." }]
  },
  {
    title: "Sathyam's Kerala Classical Gala",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1429514513361-8fa32282fd5f?w=800",
    date: "2026-10-05T00:00:00Z",
    time: "6:00 PM",
    location: "Nehru Stadium, Thiruvananthapuram, Kerala",
    rating: "4.6",
    description: "A grand Carnatic classical concert with Kerala's finest vocalists and instrumentalists — mridangam, veena, violin, and flute in a rare ensemble.",
    price: 70000,
    organizer: "Swathi Music Academy",
    features: ["Carnatic Masters", "Rare Ensemble Format", "Open to All Ages"],
    crew: [{ name: "Dr. M. Balamuralikrishna Jr.", role: "Lead Vocalist", img: "https://ui-avatars.com/api/?name=M+Balamuralikrishna&background=random&size=200" }],
    reviews: [{ name: "Padmini", rating: 5, comment: "Classical music at its transcendent best." }]
  },
  {
    title: "Thanseer Koothuparamba Live",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-10-12T00:00:00Z",
    time: "7:30 PM",
    location: "EMS Corporation Stadium, Kozhikode, Kerala",
    rating: "4.7",
    description: "The beloved Malayalam singer Thanseer Koothuparamba performs his chart-topping Mappila songs and evergreen hits live for the first time in Kozhikode.",
    price: 80000,
    organizer: "Media One Events",
    features: ["Fan Request Segment", "Special Surprise Guest", "Exclusive Merchandise"],
    crew: [{ name: "Thanseer Koothuparamba", role: "Singer", img: "https://ui-avatars.com/api/?name=Thanseer+Koothuparamba&background=random&size=200" }],
    reviews: [{ name: "Aziz", rating: 5, comment: "His voice carries the soul of Kerala!" }]
  },

  // ── Kerala · Events (Arena) ───────────────────────────────────────────────────
  {
    title: "Kerala Boat Race Championship",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    date: "2026-09-12T00:00:00Z",
    time: "8:00 AM",
    location: "Punnamada Lake Arena, Kochi, Kerala",
    rating: "4.9",
    description: "The spectacular Nehru Trophy Boat Race — snake boats with 100 oarsmen race through Punnamada Lake in a thrilling championship.",
    price: 40000,
    organizer: "Kerala Tourism Development Corporation",
    features: ["Waterfront VIP Gallery", "Traditional Lunch", "Folk Dance Show"],
    crew: [{ name: "Jose Mathew", role: "Race Coordinator", img: "https://ui-avatars.com/api/?name=Jose+Mathew&background=random&size=200" }],
    reviews: [{ name: "Aisha", rating: 5, comment: "Electrifying atmosphere. Bucket list experience!" }]
  },
  {
    title: "Kerala Biennale Art Festival",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
    date: "2026-09-25T00:00:00Z",
    time: "10:00 AM",
    location: "Aspinwall Arena, Kochi, Kerala",
    rating: "4.8",
    description: "The Kochi-Muziris Biennale — South Asia's largest contemporary art festival — transforms Kochi's heritage buildings into a global exhibition space.",
    price: 30000,
    organizer: "Kochi Biennale Foundation",
    features: ["International Artists", "Heritage Venue Tours", "Artist Talks"],
    crew: [{ name: "Riyas Komu", role: "Festival Director", img: "https://ui-avatars.com/api/?name=Riyas+Komu&background=random&size=200" }],
    reviews: [{ name: "Nandita", rating: 5, comment: "Art that genuinely challenges and transforms you." }]
  },
  {
    title: "Kerala Yoga Retreat & Festival",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    date: "2026-10-02T00:00:00Z",
    time: "6:00 AM",
    location: "Marari Beach Arena, Alappuzha, Kerala",
    rating: "4.7",
    description: "A 3-day yoga and wellness festival on Kerala's most pristine backwater beach — morning yoga, Ayurveda workshops, meditation, and sattvic food.",
    price: 55000,
    organizer: "Yoga Alliance India",
    features: ["Beach Yoga Sessions", "Ayurveda Consultation", "Sattvic Meals Included"],
    crew: [{ name: "Guru Shivananda", role: "Lead Yogi", img: "https://ui-avatars.com/api/?name=Guru+Shivananda&background=random&size=200" }],
    reviews: [{ name: "Sarah", rating: 5, comment: "Three days of pure peace and transformation." }]
  },
  {
    title: "Thrissur Pooram Spectacle",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800",
    date: "2026-10-10T00:00:00Z",
    time: "4:00 PM",
    location: "Thekkinkadu Maidan Arena, Thrissur, Kerala",
    rating: "5.0",
    description: "Experience Kerala's most spectacular temple festival live — 100 caparisoned elephants, parasol displays, percussion ensembles, and fireworks at midnight.",
    price: 50000,
    organizer: "Thrissur Pooram Committee",
    features: ["Elephant Procession", "Fireworks Show", "Cultural Night"],
    crew: [{ name: "Pooram Committee Chair", role: "Event Organizer", img: "https://ui-avatars.com/api/?name=Pooram+Committee&background=random&size=200" }],
    reviews: [{ name: "Thomas", rating: 5, comment: "The greatest show on earth. No exaggeration." }]
  },
  {
    title: "Kerala Spice Trail Run",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    date: "2026-10-18T00:00:00Z",
    time: "6:30 AM",
    location: "Periyar Arena, Thekkady, Kerala",
    rating: "4.6",
    description: "A scenic 15K trail run through Thekkady's spice plantations — cardamom, pepper, and cinnamon groves as your backdrop with elephant sightings possible.",
    price: 35000,
    organizer: "Adventure Kerala",
    features: ["Scenic Trail", "Spice Farm Visit", "Wildlife Guide"],
    crew: [{ name: "Biju Thampi", role: "Trail Director", img: "https://ui-avatars.com/api/?name=Biju+Thampi&background=random&size=200" }],
    reviews: [{ name: "Meghna", rating: 5, comment: "Ran through a spice garden. Dreams do come true!" }]
  },

  // ════════════════════════════════════════════════════════════════════════════
  //  RAJASTHAN — 20 events
  // ════════════════════════════════════════════════════════════════════════════

  // ── Rajasthan · Movies (Theatre) ─────────────────────────────────────────────
  {
    title: "KGF Chapter 3 — Rajasthan Premiere",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800",
    date: "2026-09-01T00:00:00Z",
    time: "Various Timings",
    location: "Miraj Cinemas Theatre, Jaipur, Rajasthan",
    rating: "4.8",
    description: "Rocky's legacy continues in this explosive third installment of the KGF saga. Yash returns with unmatched power, fury, and style.",
    price: 42000,
    organizer: "Hombale Films",
    features: ["4K Laser Projection", "Luxury Recliners", "VIP Lounge"],
    crew: [
      { name: "Prashanth Neel", role: "Director", img: "https://ui-avatars.com/api/?name=Prashanth+Neel&background=random&size=200" },
      { name: "Yash", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Yash&background=random&size=200" }
    ],
    reviews: [{ name: "Kiran", rating: 5, comment: "Rocky Bhai is back and better than ever!" }]
  },
  {
    title: "Bollywood Classic Remastered",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    date: "2026-08-10T00:00:00Z",
    time: "Various Timings",
    location: "Raj Mandir Cinema Theatre, Jaipur, Rajasthan",
    rating: "4.9",
    description: "The iconic Raj Mandir Cinema hosts a remastered 4K screening of Sholay — India's greatest film restored to its original magnificence.",
    price: 30000,
    organizer: "Ramesh Sippy Foundation",
    features: ["Remastered 4K", "Heritage Cinema Experience", "Anniversary Booklet"],
    crew: [{ name: "Ramesh Sippy", role: "Original Director", img: "https://ui-avatars.com/api/?name=Ramesh+Sippy&background=random&size=200" }],
    reviews: [{ name: "Sundar", rating: 5, comment: "Gabbar is still the greatest villain ever!" }]
  },
  {
    title: "Salman Khan 45th Film",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800",
    date: "2026-08-22T00:00:00Z",
    time: "Various Timings",
    location: "Cinepolis Vivek Theatre, Jodhpur, Rajasthan",
    rating: "4.7",
    description: "Bhai is back in his 45th film — an action-packed entertainer set against the majestic backdrop of Rajasthan's forts and deserts.",
    price: 38000,
    organizer: "Salman Khan Films",
    features: ["Fan-First Shows", "Bhai Merchandise", "Backstage Photo Experience"],
    crew: [
      { name: "Kabir Khan", role: "Director", img: "https://ui-avatars.com/api/?name=Kabir+Khan&background=random&size=200" },
      { name: "Salman Khan", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Salman+Khan&background=random&size=200" }
    ],
    reviews: [{ name: "Suraj", rating: 5, comment: "Bhai never fails to entertain!" }]
  },
  {
    title: "Sanjay Leela Bhansali Epic",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800",
    date: "2026-09-12T00:00:00Z",
    time: "Various Timings",
    location: "INOX Jaipur Theatre, Jaipur, Rajasthan",
    rating: "4.9",
    description: "Sanjay Leela Bhansali's newest grand period drama set in Rajputana — extravagant sets, haunting music, and stunning performances.",
    price: 45000,
    organizer: "Bhansali Productions",
    features: ["Grand Premiere", "Limited Edition Stills", "Director's Commentary"],
    crew: [
      { name: "Sanjay Leela Bhansali", role: "Director", img: "https://ui-avatars.com/api/?name=Sanjay+Bhansali&background=random&size=200" },
      { name: "Ranveer Singh", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Ranveer+Singh&background=random&size=200" }
    ],
    reviews: [{ name: "Rani", rating: 5, comment: "Visual poetry — Bhansali at his most magnificent." }]
  },
  {
    title: "Hrithik Roshan War 3",
    type: "featured",
    category: "movie",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800",
    date: "2026-09-25T00:00:00Z",
    time: "Various Timings",
    location: "PVR INOX Theatre, Udaipur, Rajasthan",
    rating: "4.7",
    description: "Hrithik Roshan returns in the action franchise War — bigger, bolder, and shot across the spectacular desert terrains of Rajasthan.",
    price: 40000,
    organizer: "Yash Raj Films",
    features: ["Rajasthan Special Screening", "Action Reel Preview", "VIP Premiere Night"],
    crew: [
      { name: "Siddharth Anand", role: "Director", img: "https://ui-avatars.com/api/?name=Siddharth+Anand&background=random&size=200" },
      { name: "Hrithik Roshan", role: "Lead Actor", img: "https://ui-avatars.com/api/?name=Hrithik+Roshan&background=random&size=200" }
    ],
    reviews: [{ name: "Priya", rating: 5, comment: "Hrithik's action sequences defy reality!" }]
  },

  // ── Rajasthan · Shows (Hall) ──────────────────────────────────────────────────
  {
    title: "Rajasthan Heritage Drama Night",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    date: "2026-09-05T00:00:00Z",
    time: "8:00 PM",
    location: "Jawahar Kala Kendra Hall, Jaipur, Rajasthan",
    rating: "4.5",
    description: "A spectacular Rajasthani heritage drama showcasing the culture, bravery, and colour of the royal state — traditional costumes and folk instruments.",
    price: 55000,
    organizer: "Rajasthan Tourism Board",
    features: ["Folk Art Exhibition", "Traditional Dinner", "Heritage Photography"],
    crew: [{ name: "Rajan Sharma", role: "Stage Director", img: "https://ui-avatars.com/api/?name=Rajan+Sharma&background=random&size=200" }],
    reviews: [{ name: "Pradeep", rating: 5, comment: "A beautiful window into Rajasthan's royal past." }]
  },
  {
    title: "Rajputana Puppet Theatre",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800",
    date: "2026-09-16T00:00:00Z",
    time: "7:00 PM",
    location: "Albert Hall Cultural Hall, Jaipur, Rajasthan",
    rating: "4.7",
    description: "The traditional Kathputli puppet art of Rajasthan — a mesmerizing show of hand-crafted puppets enacting tales of valor from Rajputana history.",
    price: 45000,
    organizer: "Rajasthan Shilp Sansthan",
    features: ["Craft Workshop", "Traditional Music", "Children's Special Segment"],
    crew: [{ name: "Pokar Bhat", role: "Master Puppeteer", img: "https://ui-avatars.com/api/?name=Pokar+Bhat&background=random&size=200" }],
    reviews: [{ name: "Anjali", rating: 5, comment: "The oldest art form of Rajasthan preserved perfectly." }]
  },
  {
    title: "Sunil Grover Comedy Dhamaal",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    date: "2026-09-24T00:00:00Z",
    time: "7:30 PM",
    location: "Jawahar Circle Hall, Jodhpur, Rajasthan",
    rating: "4.6",
    description: "Sunil Grover brings his most beloved characters — Dr. Mashoor Gulati and Rinku Devi — to the stage in a live comedy extravaganza.",
    price: 75000,
    organizer: "Weekend Productions",
    features: ["Character Costume Show", "Fan Interaction", "Stand-up + Sketch Combo"],
    crew: [{ name: "Sunil Grover", role: "Comedian & Actor", img: "https://ui-avatars.com/api/?name=Sunil+Grover&background=random&size=200" }],
    reviews: [{ name: "Manish", rating: 5, comment: "Dr. Mashoor Gulati in person is even funnier!" }]
  },
  {
    title: "Desert Mystic Sufi Night",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-10-03T00:00:00Z",
    time: "9:00 PM",
    location: "Mehrangarh Fort Hall, Jodhpur, Rajasthan",
    rating: "4.9",
    description: "A transcendent Sufi music night at the majestic Mehrangarh Fort — qawwals, mystic devotional music echoing across the blue city skyline.",
    price: 90000,
    organizer: "RIFF Trust",
    features: ["Fort Illumination", "Pre-show Fort Walk", "Sufi Poetry Recital"],
    crew: [{ name: "Nooran Sisters", role: "Sufi Vocalists", img: "https://ui-avatars.com/api/?name=Nooran+Sisters&background=random&size=200" }],
    reviews: [{ name: "Fatima", rating: 5, comment: "Against Mehrangarh's walls — pure transcendence." }]
  },
  {
    title: "Rajasthan Comedy Circuit",
    type: "featured",
    category: "show",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-10-10T00:00:00Z",
    time: "7:00 PM",
    location: "Birla Auditorium Hall, Jaipur, Rajasthan",
    rating: "4.5",
    description: "Rajasthan's rising stand-up comedy scene showcased — five emerging Marwari and Hindi comedians performing original sets.",
    price: 50000,
    organizer: "Jaipur Comedy Club",
    features: ["5 New Voices", "Hindi & Marwari Sets", "Open Mic After-party"],
    crew: [{ name: "Mahesh Khatri", role: "Show Curator", img: "https://ui-avatars.com/api/?name=Mahesh+Khatri&background=random&size=200" }],
    reviews: [{ name: "Golu", rating: 5, comment: "Rajasthan has serious comedy talent!" }]
  },

  // ── Rajasthan · Concerts (Stadium) ────────────────────────────────────────────
  {
    title: "Arijit Singh Unplugged",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1429514513361-8fa32282fd5f?w=800",
    date: "2026-09-20T00:00:00Z",
    time: "7:00 PM",
    location: "Sawai Mansingh Stadium, Jaipur, Rajasthan",
    rating: "5.0",
    description: "Arijit Singh performs an intimate unplugged concert — Bollywood's most beloved voice with acoustic arrangements under the Jaipur sky.",
    price: 130000,
    organizer: "SoundHouse Events",
    features: ["Acoustic Stage", "Intimate Format", "VIP Meet & Greet"],
    crew: [{ name: "Arijit Singh", role: "Singer & Performer", img: "https://ui-avatars.com/api/?name=Arijit+Singh&background=random&size=200" }],
    reviews: [{ name: "Shreya", rating: 5, comment: "Every song felt sung just for me. Magical." }]
  },
  {
    title: "Lata Mangeshkar Tribute Concert",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800",
    date: "2026-09-28T00:00:00Z",
    time: "6:30 PM",
    location: "SMS Stadium, Jaipur, Rajasthan",
    rating: "4.9",
    description: "A grand tribute to the Nightingale of India — Asha Bhosle and Kumar Sanu perform Lata ji's most iconic songs in a 3-hour orchestral tribute.",
    price: 110000,
    organizer: "Saregama Entertainment",
    features: ["Full Orchestra", "Rare Recordings Screening", "Collector's Vinyl"],
    crew: [
      { name: "Asha Bhosle", role: "Special Guest Performer", img: "https://ui-avatars.com/api/?name=Asha+Bhosle&background=random&size=200" },
      { name: "Kumar Sanu", role: "Performer", img: "https://ui-avatars.com/api/?name=Kumar+Sanu&background=random&size=200" }
    ],
    reviews: [{ name: "Padma", rating: 5, comment: "Asha ji singing in Lata di's memory was heartbreaking and beautiful." }]
  },
  {
    title: "Nooran Sisters Desert Qawwali",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    date: "2026-10-05T00:00:00Z",
    time: "8:00 PM",
    location: "Sam Sand Dunes Stadium, Jaisalmer, Rajasthan",
    rating: "4.8",
    description: "The electrifying Nooran Sisters perform a Qawwali concert under the open desert sky — sand dunes, full moon, and devotional music at its most powerful.",
    price: 100000,
    organizer: "Jaisalmer Music Festival",
    features: ["Desert Outdoor Venue", "Camel Ride", "Desert Camping Package"],
    crew: [{ name: "Nooran Sisters", role: "Qawwali Performers", img: "https://ui-avatars.com/api/?name=Nooran+Sisters&background=random&size=200" }],
    reviews: [{ name: "Khalid", rating: 5, comment: "Qawwali under the stars in the desert — heaven." }]
  },
  {
    title: "Shankar-Shaman Folk Fusion",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800",
    date: "2026-10-12T00:00:00Z",
    time: "7:00 PM",
    location: "Umaid Bhawan Palace Stadium, Jodhpur, Rajasthan",
    rating: "4.7",
    description: "A unique concert fusing Rajasthani folk instruments (sarangi, rawanhattha, morchang) with electronic soundscapes — an experiment in sound at Umaid Bhawan.",
    price: 85000,
    organizer: "Jodhpur RIFF Trust",
    features: ["Heritage Venue", "Folk Instrument Demo", "Artist Workshop"],
    crew: [{ name: "Aneesh Pradhan", role: "Music Director", img: "https://ui-avatars.com/api/?name=Aneesh+Pradhan&background=random&size=200" }],
    reviews: [{ name: "Seema", rating: 5, comment: "The rawanhattha solo was utterly hypnotic." }]
  },
  {
    title: "Mika Singh Saawan Special",
    type: "featured",
    category: "concert",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    date: "2026-10-18T00:00:00Z",
    time: "7:30 PM",
    location: "Barkatullah Khan Stadium, Jodhpur, Rajasthan",
    rating: "4.6",
    description: "Mika Singh brings his high-energy party concert to Rajasthan — Bollywood hits, bhangra, and an atmosphere of pure celebration.",
    price: 80000,
    organizer: "Star Entertainment",
    features: ["High-Energy Show", "Bhangra Zone", "Fan Dance Competition"],
    crew: [{ name: "Mika Singh", role: "Singer & Performer", img: "https://ui-avatars.com/api/?name=Mika+Singh&background=random&size=200" }],
    reviews: [{ name: "Balwinder", rating: 5, comment: "Nobody throws a party like Mika bhai!" }]
  },

  // ── Rajasthan · Events (Arena) ────────────────────────────────────────────────
  {
    title: "Desert Night Run Jaipur",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800",
    date: "2026-09-25T00:00:00Z",
    time: "5:00 AM",
    location: "Nahargarh Fort Arena, Jaipur, Rajasthan",
    rating: "4.7",
    description: "A breathtaking 10K night run from before dawn through Jaipur's old city, ending at the majestic Nahargarh Fort as the sun rises.",
    price: 35000,
    organizer: "Rajasthan Running Club",
    features: ["Finisher Medal", "Sunrise Breakfast", "Heritage Route"],
    crew: [{ name: "Mohit Rathore", role: "Race Director", img: "https://ui-avatars.com/api/?name=Mohit+Rathore&background=random&size=200" }],
    reviews: [{ name: "Nisha", rating: 5, comment: "Running through the Pink City at dawn was surreal." }]
  },
  {
    title: "Jaipur Literature Festival",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    date: "2026-10-01T00:00:00Z",
    time: "9:00 AM",
    location: "Diggi Palace Arena, Jaipur, Rajasthan",
    rating: "5.0",
    description: "The world's largest free literary festival returns to Jaipur — 500+ speakers, translators, thinkers, and artists from 50 countries over 5 days.",
    price: 20000,
    organizer: "Teamwork Arts",
    features: ["500+ Speakers", "Bookshop Village", "Cultural Evenings"],
    crew: [{ name: "William Dalrymple", role: "Co-Director", img: "https://ui-avatars.com/api/?name=William+Dalrymple&background=random&size=200" }],
    reviews: [{ name: "Anushka", rating: 5, comment: "The most intellectually stimulating 5 days of my life." }]
  },
  {
    title: "Pushkar Camel Fair",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
    date: "2026-10-08T00:00:00Z",
    time: "7:00 AM",
    location: "Pushkar Fair Arena, Pushkar, Rajasthan",
    rating: "4.8",
    description: "The world's largest camel fair — 50,000 camels, horses, and cattle traded under the desert sky, with folk performances, competitions, and the sacred Pushkar lake.",
    price: 25000,
    organizer: "Rajasthan Tourism",
    features: ["Camel Race", "Cultural Performances", "Fair Photography Walk"],
    crew: [{ name: "Fair Committee Head", role: "Event Director", img: "https://ui-avatars.com/api/?name=Fair+Committee&background=random&size=200" }],
    reviews: [{ name: "Michael", rating: 5, comment: "Unlike anything else on earth. Truly unique." }]
  },
  {
    title: "Rajasthan Polo Cup",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    date: "2026-10-15T00:00:00Z",
    time: "3:00 PM",
    location: "Jaipur Polo Ground Arena, Jaipur, Rajasthan",
    rating: "4.7",
    description: "The most prestigious polo tournament in India — six elite teams compete on the hallowed grounds of Jaipur Polo Club, established 1862.",
    price: 60000,
    organizer: "Jaipur Polo Club",
    features: ["VIP Marquee", "Elephant Polo Warm-up", "Heritage Sundowner"],
    crew: [{ name: "Col. Ranjit Singh", role: "Tournament Director", img: "https://ui-avatars.com/api/?name=Ranjit+Singh&background=random&size=200" }],
    reviews: [{ name: "Oliver", rating: 5, comment: "The most elegant sport experience imaginable." }]
  },
  {
    title: "Rann of Rajasthan Kite Festival",
    type: "featured",
    category: "event",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    date: "2026-10-22T00:00:00Z",
    time: "9:00 AM",
    location: "Bikaner Fair Arena, Bikaner, Rajasthan",
    rating: "4.6",
    description: "The sky over Bikaner transforms into a canvas of colour — 10,000+ kites from 30 countries compete in India's most spectacular international kite festival.",
    price: 22000,
    organizer: "Rajasthan Kite Association",
    features: ["International Teams", "Kite Making Workshop", "Desert Night Viewing"],
    crew: [{ name: "Bhupesh Sharma", role: "Festival Director", img: "https://ui-avatars.com/api/?name=Bhupesh+Sharma&background=random&size=200" }],
    reviews: [{ name: "Anuj", rating: 5, comment: "A sky full of dragons, serpents, and mantas. Unforgettable!" }]
  }
];